# Maven
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure Pass - Sponsorship(ea5248e4-e3d7-40f7-b92c-a01e0528783d)'
    appType: 'webAppLinux'
    WebAppName: 'myjavaa'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    appType: 'webAppLinux'
    WebAppName: 'mywebapp13'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- dependabot/maven/org.springframework.boot-spring-boot-starter-web-2.5.12

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
